### DISCUSSION TITLE
Just wondering when a 4.x "Stable" version is targeted for 🙌

### DISCUSSION THREAD

**Discussion by tsavo-at-pieces** [onepub-dev/dcli#233] [Q&A]
Edit by bsutton the DCLI maintainer.

I've added a wiki page on outstanding issues. If you can pick one of these up let me know and I will mark it as in progress.

https://github.com/onepub-dev/dcli/wiki

Original question:

Would love to know how "stable" the core functionality of 4.x Alpha is and if it is too early to adopt/what we can do to help contribute & or create a migration guide @bsutton! 

Absolutely huge fan of this entire project and I'd love to jump in where I can. Primarily working on server-side AOT GRPC engines and using DCLI to manage all types of things from automated CI/CD to DevEx @ [pieces.app](https://pieces.app) 🙌

**Comment by bsutton** [comment]
Thanks for the interest.

So where are things at?

There are a couple of major pieces still to be done.

I'm working on the process execution paths .run .start etc and hoping to
have these working next week.

I still need a solution for namedlocks. I'm thinking of using native
locking mechanisms e.g. lock from the posix package and something from the
win32 package.


If you want to have a crack at solving that?

I also need a windows implementation of the mailbox code.

Moderation guide would also be great.

 the unit test need to be worked through to insure they are all functioning
but this probably needs to wait  until I've completed work in process
execution.

A review of the API looking for inconsistencies and missing outdated API
documentation.

A review of what functions belong in each of the new sub packages.

General sanity checks.

Key changes
the breaking up into multiple packages with the CLI tooling now in dcli_sdk.

A number of functions have been renamed with a Async suffix.

...


I'm using the alpha in some of my code. The core hurdle is the process
execution and the reality that I might still tweak the APIs given the above
reviews.

**Reply by tsavo-at-pieces** [reply]
Okay fantastic - 

I'll likely kick off a migration to the Alpha and scope out critical missing implementations that I can get a draft for. 

Do we have a location where some of this stuff is being tracked. Happy to help out with a little PM as well. 

Cheers, 
-Tsavo

**Comment by bsutton** [comment]
I don't have a specific spot for tracking progress.

If it suites we could just post updates here, the other option is to create a discussion or I could start a web page.
Happy to give you contributor access provided all code changes come via a pr.

Thoughts?
Brett

**Comment by passsy** [comment]
Is the plan to move most functions to async functions or is there a workaround to continue with the sync API?

**I'm all for moving to async!**
Whenever I teach writing cli scripts with [sidekick](https://github.com/phntmxyz/sidekick), I get many questions about the missing `await` for dcli methods. From my experience, people expect processes to be Futures and would `await` them without any problem. The sync methods feel alien in the Dart world and add unnecessary complexity.

The whole `waitFor*` was a nice experiment. I honestly respect your efforts! But I think it failed to bring any reward for the users of dcli. Additionally, it is - and has always been - a major roadblock for new dcli releases, which comes up way too often after new Dart releases. I'm confident that dcli would be much easier to maintain with an async API.

**Comment by bsutton** [comment]
@passsy so the async/sync debate is a really interesting question that has kept me up at nights.

A core reason for going sync originally was that dart did a terrible job reporting missing awaits and in cli programming one missing await could cause serious data loss.  So going sync side stepped this issue.

Since then dart has gotten much better at reporting missing awaits (providing you use the correct lints)  with a few exceptions.

For much of the existing api we have  been able to retain it's sync style. There were quite a few xxxxSync methods in the dart api that I wasn't taking advantage of.

Here are the big issues that I'm working through and could do with some help on.

**Review of callbacks**
There are some methods that I'm still uncertain about due to the above missing await issues. The key methods are those that start with 'withXXXX' such as withEnvironment or withTempDir (essentially any method that allows the user to pass a callback).

If the 'action/callback' argument to one of these makes an async call and you don't mark the callback as async, then you are in for a world of grief - for instance the withTempDir function will delete the temp dir before your async callback completes.

At this point I've created alternate variants of these methods: 'withTempDir' and 'withTempDirAsync' and added a warning to the sync version. I'm still not convinced that leaving the sync version in the api is safe (this is also an issue with the 'ask' function validator callbacks). I have added warnings to the sync version and a 'see also' to the async version, but I'm not certain if this is enough.

Thoughts?

**Sync vs Async processes.**
As to the conversation around sync/async on processes.

The stream method (which was experimental) is moving to async - because it never made sense for it to be sync.

My feeling is that I should still support the sync versions of the start/run functions (and friends) and I believe that I have  path forward on these methods (functions like .run are already working).
Removing support for these would be fairly painful for the user base. Apart from the usage of the mailbox it does look the new implementations will be simpler - I've learnt a few things on the way :)

**Mailbox support on Windows.**
The mailbox is a new class contributed by one of the dart devs that allows us to make sync calls across an isolate boundary. The new sync versions of each of the process methods uses the mailbox so they can remain synchronous.

Support for the Mailbox class (and hence sync process) on Windows  will take some more work but I think this is just find the right ffi calls for windows.
if any one wants to jump in and do some develop a windows version of the mailbox code that would be really great!!!!
Raise an issue on the dcli package if you can hope in and help.

**Mailbox macos support**
In theory the mailbox code should work on macos as is. But this needs to be tested.


I do think there is an argument for an async version of the process calls.  I did look to integrating the cli_scripts package into dcli but felt that there was an impedance mismatch in the way the api is written.

At this point I'm inclined to keep pushing on getting the sync version of the process calls working - because I can see the light at then end of the tunnel and then review the async question post 4.x.

**Review/cleanup of pubspec_manager**
The other task that I could do with some help on is the pubspec_manager package. I've written this to replace the pubspec (and it's fork pubspec2) package.  I learnt today that the pubspec package has been abandoned and as the maintainer of pubspec2, I have no intention of continuing support.  One of the key reasons is that the pubspec package didn't retain comments (and the api wasn't very friendly).
The pubspec_manager package is in alpha but really needs a review of the api and I'm a little concerned that the code is overly complex.  So if anyone is willing to hop in and give some feedback or contribute to the work that would be a big help.
Raise an issue on the pubspe_manager package to indicate your interest.

**Linter**
Given the more async nature of scripts that will be developed going forward - the user developed scripts will need to be more async as they also can't use waitfor,  then I think it would be useful to have an official dcli lint package.
I maintain the lint_hard package - but it's probably a little too aggressive - it includes every non-conflicting lint.
I would love to see a linter developed that pushes for strict typing and and includes all of the missing await lints.
This would be a nice little task for someone. You can have a look at the lint_hard package as a starting point. https://pub.dev/packages/lint_hard

**Review of package structure**
You may have noticed that I've split dcli into a number of smaller packages.
The main 'dcli' package will still export all of the existing functions but if you need a small subset of functionality you can directly use one of the sub packages.
I've also moved dcli's own cli tooling to a new package 'dcli_sdk' so to install the dcli cli tooling you need to run 'pub global activate dcli_sdk'.
This will allow us to lock down the dependency versions for dcli_sdk - so that it always works - whilst leaving the dcli libraries version constraints open.    

It would be useful if someone could review the set of sub-packages for the set of methods each exposes and whether each method is in the correct package. 


I think that is all of the big issues.

**Reply by tsavo-at-pieces** [reply]
For others - Mailbox support is completed and tested on MacOS (Intel & Apple Silicon), Linux, and Windows. See merged PR [here](https://github.com/onepub-dev/dcli/pull/234) for additional details. It leverages the [native_synchronization](https://pub.dev/packages/native_synchronization) package awesomely authored by @mraleph 🙌

> Mailbox support on Windows. 
> The mailbox is a new class contributed by one of the dart devs that allows us to make sync calls across an isolate boundary. The new sync versions of each of the process methods uses the mailbox so they can remain synchronous.
> 
> Support for the Mailbox class (and hence sync process) on Windows will take some more work but I think this is just find the right ffi calls for windows.
> if any one wants to jump in and do some develop a windows version of the mailbox code that would be really great!!!!
> Raise an issue on the dcli package if you can hope in and help.
> 

> Mailbox macos support
> In theory the mailbox code should work on macos as is. But this needs to be tested.
> 
> I do think there is an argument for an async version of the process calls. I did look to integrating the cli_scripts package into dcli but felt that there was an impedance mismatch in the way the api is written.
> 
> At this point I'm inclined to keep pushing on getting the sync version of the process calls working - because I can see the light at then end of the tunnel and then review the async question post 4.x.
>

**Comment by tsavo-at-pieces** [comment]
Hey all! 

@bsutton do you have an idea of where the mailboxes are currently being used? (I can also go dig but a direction pointer would be great)

Here was some quick notes I got from ChatGPT to start evaluating the usage of mailboxes:

> To make the code work on Windows, you would need to adapt it to use Windows-specific synchronization primitives or use a cross-platform abstraction that can handle both POSIX and Windows environments. Dart's FFI (Foreign Function Interface) allows you to call into C-style shared libraries, so you could theoretically use it to call Windows API functions for thread synchronization and IPC. However, this specific implementation, as it stands, relies on POSIX APIs (pthread_mutex_lock, pthread_cond_wait, etc.) and would not directly work on Windows without modification.
> 
> If you're looking to achieve similar functionality (inter-isolate communication with synchronization) on Windows in Dart, consider the following approaches:
> 
> Abstract Over POSIX and Windows Primitives: Create an abstraction layer that uses POSIX primitives on UNIX-like systems and Windows primitives on Windows. This would involve conditional compilation or runtime checks to determine which set of functions to use.
> 
> Use Cross-Platform Libraries: Look for cross-platform libraries or packages in Dart that abstract away the differences between POSIX and Windows for threading and synchronization. This could simplify your code and make it portable across different operating systems.
> 
> Dart-Specific Mechanisms: For inter-isolate communication, consider leveraging Dart's built-in mechanisms, such as Isolate channels (SendPort/ReceivePort), which are designed to work cross-platform, including Windows, without needing to directly use system-level threading and synchronization primitives.
> 
> Windows API via FFI: If you need to use specific Windows features not covered by Dart's standard library or third-party packages, you can directly call Windows API functions using Dart's FFI. For example, you could use Windows Mutexes, Events, or Condition Variables for synchronization between threads or isolates.
> 
> Adjusting the code to work on Windows would require significant changes, particularly replacing the POSIX threading functions with their Windows counterparts or adopting a completely different approach for synchronization and IPC that's more aligned with Dart's cross-platform capabilities.

Happy to jump in here as I have had a lot of experience with Dart FFI but definitely wanna plan this out a bit to know exactly how it's intending to be used and how we might make a cross platform abstraction.

Let me know thoughts & happy to chat live as well. 
-T

**Reply by tsavo-at-pieces** [reply]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postthreadmessagea

Perhaps?

Also super interesting:
https://github.com/eneural-net/async_task/blob/master/lib/src/async_task_shared_pointer.dart
https://github.com/eneural-net/async_task/blob/master/lib/src/async_task_shared_data.dart

Note that this is lacking a 'mutex' implementation to give the main thread true ownership:
https://github.com/eneural-net/async_task/blob/e30273fac4fbff8472c0bbaa9066ce3298acc158/lib/src/async_task_shared_pointer.dart#L395

**Reply by tsavo-at-pieces** [reply]
Status update - it seems that anything using 'CommandLineRunner.process' uses synchronous mailboxes at the moment. 

I can confirm that it works great on MacOS both Intel & Apple Silicon as well as Ubuntu ✅

It looks like we need some conditional code for windows which uses the proper win32 API via FFI i.e. per my link above. 

Let me know thoughts on how we might want to proceed and I can put some time into this this week 🤝

-T

**Reply by tsavo-at-pieces** [reply]
Last bit of research for the day but perhaps THIS is what we're looking for:

https://github.com/dart-lang/native_synchronization/blob/main/lib/windows.dart

https://github.com/dart-lang/native_synchronization/blob/main/lib/src/bindings/winapi.dart

https://pub.dev/packages/native_synchronization

**Comment by bsutton** [comment]
> Status update - it seems that anything using 'CommandLineRunner.process' uses synchronous mailboxes at the moment.

At this point that is the only place that I intend to use mailboxes. 

Good to hear its working on mac os. I do my primary testing on ubuntu.

> It looks like we need some conditional code for windows which uses the proper win32 API via FFI i.e. per my link above.
Exactly this.

> https://github.com/dart-lang/native_synchronization

Given that the mailbox code was contributed by @mraleph there might be an argument that we directly use the native_synchronization package and perhaps contribute some of my changes back to that repo.

Only issues it that it is marked experimental so may go away at some point.
I guess we could use the existing package and if it goes away then we merge the required code into dcli.

Happy for you to make the call.

**Reply by mraleph** [reply]
I am planning to promote the package out of experimental area relatively soon (next quarter). I would like to first update API around how these things are shared between isolates within the same isolate group by piggybacking on some new VM specific stuff we are adding (this would allow us to drop things like `toSendable` and `materialize` and make lifetime more clear).

**Reply by tsavo-at-pieces** [reply]
@bsutton I'll be implementing this today and I'll let you know how it goes! 

I'll start by refactoring the code to use the package directly. 

@mraleph great to hear & looking forward to it 🤝 In the meantime I'll be sure to report back anything I run into or suggestions for areas of improvement 🫡

**Comment by tsavo-at-pieces** [comment]
@bsutton the refactor & implementation is complete. I have tested it internally with our CI/CD. We are smooth sailing.

This test passes with flying colors:  .dcli/test/src/process/process/synchronous_test.dart

Both locally:
<img width="1113" alt="Screenshot 2024-03-20 at 3 38 07 PM" src="https://github.com/onepub-dev/dcli/assets/102485237/e1c903ec-5722-440e-a915-afe5f30b9068">

And on all platforms:
<img width="763" alt="Screenshot 2024-03-20 at 3 34 40 PM" src="https://github.com/onepub-dev/dcli/assets/102485237/e5ca696f-3c04-4efb-ba86-5c4899e1b7c7">

Will make a PR shortly in a fresh fork from master 🤝

**Comment by bsutton** [comment]
Wow, that's fantastic.

Appreciate the work.

If you are looking for another challenge, NamedLock is the next issue. It
uses a TCP socket as a interprocess lock (in the hardlock function).  We
need to change this to a native lock function on all platforms. The posix
package may have a lock method exposed ( I'm they maintainer of the posix
package so we can patch that if necessary).

@mralph appreciate you contributions. We wouldn't have got this far without
your work!

**Reply by tsavo-at-pieces** [reply]
+1 @mraleph !

@bsutton - can absolutely look into this. 

Question - does the shell detection for Windows (PowerShell & Cmd) need some love? For some reason within a GitHub actions runner it refuses to recognize that the process isPrivileged and resolves to an unknown shell. 

That said I have some checks that verify that the Windows runner is indeed privileged:

```yaml

      - name: Check if running as admin [Windows - Powershell]
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          $is_admin = [bool](([System.Security.Principal.WindowsIdentity]::GetCurrent()).groups -match "S-1-5-32-544")
          echo "Is Admin: $is_admin"
        shell: pwsh

      - name: Check if running as admin [Windows - CMD]
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          net session >nul 2>&1
          if %errorLevel% == 0 (
            echo "Is Admin: true"
          ) else (
            echo "Is Admin: false"
          )
        shell: cmd
 ```

Also - when installing DCLI on Windows does it install a compiled dcli.exe/dcli_install.exe/dcli_complete.exe or does it install an AOT snapshot?

Would love to know how I can activate globally DCLI from a local path and ensure that it uses locally compiled executables from source:

I am using this command: 

```dart pub global activate -spath ./packages/external_dependencies/dcli/dcli_sdk --overwrite```

Yet right now it looks like it still uses some external binaries.. My workaround on other platforms (besides windows) is to compile the binaries from source and then relocate them manually to the .pub-cache/bin after running `dart pub global activate...` and ```dcli install```


Let me know if there are solutions/known issues that may need addressing in this area - happy to make a PR if you point me in the right direction. 

Perhaps the InstallCommand can take a path to the local bin?

Nevertheless - I'll look into the NamedLocks!  Also - I'd love to hop on a google meet sometime and show you what I'm working on. 

DCLI is super critical to our next generation infrastructure around GRPC and AOT binaries for pieces.app and so I'm down to help move things along in any regard 🤝

Cheers, 
-T

**Reply by tsavo-at-pieces** [reply]
@bsutton regarding a solution for named locks:

Take a look at this _relatively simple_ [rust package](https://crates.io/crates/named-lock) repo [here](https://github.com/oblique/named-lock)(1.6M Downloads) 

[lib.rs: NamedLock Implementation](https://github.com/oblique/named-lock/blob/9ddc8536c1e6884a88a402012c84eb4b5f90ce89/src/lib.rs#L69)

[windows.rs: RawNamedLock](https://github.com/oblique/named-lock/blob/9ddc8536c1e6884a88a402012c84eb4b5f90ce89/src/windows.rs#L21)

[unix.rs: RawNamedLock](https://github.com/oblique/named-lock/blob/9ddc8536c1e6884a88a402012c84eb4b5f90ce89/src/unix.rs#L15)

Note its description:

> On UNIX this is implemented by using files and [flock](https://linux.die.net/man/2/flock). The path of the created lock file will be $TMPDIR/<name>.lock, or /tmp/<name>.lock if TMPDIR environment variable is not set.
> 
> On Windows this is implemented by creating named mutex with [CreateMutexW](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexw).

I can reimplement this in Dart in about a day if it looks like a good solution. Lmk 🫡

-T

**Reply by tsavo-at-pieces** [reply]
@bsutton in addition to the named locks primitives - shall I do some enhancements on the shell detection? I believe I am still having trouble detecting if we are in powershell when running dcli install on Windows. It primarily has issues with detecting if we are in elevated permissions or not and right now resolves to unknown shell when operating in GitHub Actions on a Windows runner.

**Comment by bsutton** [comment]
Yes, please!

**Reply by tsavo-at-pieces** [reply]
Is that what we're looking for?

I can rip it 🤝

**Comment by bsutton** [comment]
Yes, that's it.

**Reply by tsavo-at-pieces** [reply]
Working on it today - should be done by EOD ✅

Will leave statuses here!

**Reply by tsavo-at-pieces** [reply]
Good morning @bsutton! 

Couple of updates - Spent a good bit of time last Thursday and Friday beginning the initial port of the Rust package above... after implementing all of the windows functionality through FFI similar to the [native_synchronization](https://pub.dev/packages/native_synchronization) package I quickly realized that the [named-lock rust package](https://crates.io/crates/named-lock) uses additional rust packages internally ... specifically [parking_lot](https://crates.io/crates/parking_lot) and [once_cell](https://crates.io/crates/once_cell)... which would also need to be ported 🫠

SOOO - game plan number two: Leverage [Flutter Rust Bridge](https://cjycode.com/flutter_rust_bridge) to bind to the rust named-lock package APIs so that they can be synchronously called in Dart. 

Fingers crossed this should be done by EOD and will move MUCH faster than porting all the rust directly into Dart. 

Will update progress here in a bit! 

Cheers,
-T

**Comment by bsutton** [comment]
> Question - does the shell detection for Windows (PowerShell & Cmd) need some love

There is certainly an issue with PowerShell. If you can take a look at it that would be appreciated.

> Would love to know how I can activate globally DCLI from a local path and ensure that it uses locally compiled executables from source:

You can do a local activation via:
cd dcli directory:
```
dart pub global activate -spath .
```

> Also - when installing DCLI on Windows does it install a compiled dcli.exe/dcli_install.exe/dcli_complete.exe or does it install an AOT snapshot?

This is a function of dart pub not a dcli function.  On windows it creates a .bat file which then runs some sort of semi compiled object - sorry can't remember the right term.

> Yet right now it looks like it still uses some external binaries.. 

What is the concern here?

If we wanted to go down the compiled path on install we probably need to do something like what the dswitch package does (I'm the maintainer). It does a aot compile and then adds the executable to the path.

> DCLI is super critical to our next generation infrastructure around GRPC and AOT binaries for pieces.app and so I'm down to help move things along in any regard 

Greatly appreciate any help I can get. DCli is a big project and so far it has mostly been just me.

**Reply by tsavo-at-pieces** [reply]
> This is a function of dart pub not a dcli function. On windows it creates a .bat file which then runs some sort of semi compiled object - sorry can't remember the right term.

I was looking into it and it seems to be assuming there is a dart runtime in place and it seems to be using the AOT Snapshot on Windows specifically. 

https://dart.dev/tools/dart-compile#aot-snapshot

Let me see if I can get it to use a decoupled and standalone AOT executable i.e. dcli.exe rather than dcli.snapshot.aot

> If we wanted to go down the compiled path on install we probably need to do something like what the dswitch package does (I'm the maintainer). It does a aot compile and then adds the executable to the path.

This might be the move - I'm actually doing this manually via Melos/GitHub Actions after running DCLI install as a temporary workaround. If we go this route it may make things a bit more isomorphic i.e. in development, for unit testing, CI/CD, and should remain unchanged for package consumers.

```yaml

      - name: Install DCLI with Elevated Privileges [Windows]
        if: steps.cache-dcli-binaries.outputs.cache-hit != 'true' && matrix.config.system_information.operating_system_family == 'windows'
        run:  dcli --verbose install --noprivileges
        shell: pwsh

      - name: Compile External DCLI Dependency [Windows]
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: melos dart:compile:dcli_executables:windows

      - name: Copy and Overwrite External DCLI Executables [Windows]
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          $program_files = $env:ProgramFiles
          $bin_dir = Join-Path -Path $program_files -ChildPath "\.dcli\bin"
          New-Item -ItemType Directory -Force -Path $bin_dir
          # log the pub cache dir which is saved in the env 
          Write-Host "PUB_CACHE_DIR: $env:PUB_CACHE_DIR"
          # log the paths of the compiled dcli, dcli_install and dcli_complete executables within .\packages\external_dependencies\dcli\dcli_sdk\bin
          $sourceDir = ".\packages\external_dependencies\dcli\dcli_sdk\bin"
          Get-ChildItem -Path $sourceDir -Filter "*.exe" -Recurse | ForEach-Object { 
             Write-Host $_.FullName 
             # Move each found .exe file to the PUB_CACHE_DIR
             Move-Item -Path $_.FullName -Destination $env:PUB_CACHE_DIR
          }

      - name: List Installed DCLI Executables [Windows]
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          # Define the source directory where you're looking for .exe files
          $sourceDir = ".\packages\external_dependencies\dcli\dcli_sdk\bin"
          
          # Get all .exe files in the source directory
          Get-ChildItem -Path $sourceDir -Filter "*.exe" -Recurse | ForEach-Object {
          # Display the full path of the current .exe file
          Write-Host "Found source executable: $($_.FullName)"
        
          # Construct the path where this .exe is expected in $env:PUB_CACHE_DIR
          $expectedPath = Join-Path -Path $env:PUB_CACHE_DIR -ChildPath $_.Name
          
          # Check if the executable exists in $env:PUB_CACHE_DIR
          if (Test-Path $expectedPath) {
          Write-Host "✅ $($_.Name) is also found in $env:PUB_CACHE_DIR"
          } else {
            Write-Host "⛔️ $($_.Name) is NOT found in $env:PUB_CACHE_DIR. Check if it is installed correctly."
            }
          }


```
