### ISSUE TITLE
Tutorial version dcli 0.51.0 do not work (win11 64bit)

### ISSUE THREAD

**Issue by Tranberry** [onepub-dev/dcli#201]
**Describe the bug**
Version in https://dcli.onepub.dev/writing-your-first-script will break when hidden in set to true:
```dart
var example = ask('password:', hidden: true);
```

on a windows machine hitting `enter`/`return` **will just register as an additional keystroke instead of 'submitting' the hidden string**.

**To Reproduce**
Copy this into your `pubspec.yaml`
```yaml
name: hello_world
description: My first app that does bugger all.

dependencies:
  dcli: ^0.51.0
```

**Expected behavior**
I would expect the tutorial to be more newbi friendly and not make us set a broken version of `dcli` for it.
