### ISSUE TITLE
dcli:2.2.4 requires Dart 3.0 (accidentally breaking)

### ISSUE THREAD

**Issue by passsy** [onepub-dev/dcli#214]
I have the following pubspec.yaml

```
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dcli: ^2.2.0
```

`pub upgrade` pulls `dcli: 2.2.4` which requires Dart 3.0. I can't compile my app with `Dart 2.19.6`. This breaks the semver contract.

<img width="820" alt="Screen-Shot-2023-05-30-14-46-44 03" src="https://github.com/onepub-dev/dcli/assets/1096485/f80bc0fd-0e36-49db-a6aa-71aeca18b212">

Please release `dcli:2.2.5` and make it `Dart 2.19` compatible again.
Do a breaking change (dcli:3.0.0) when upgrading to `Dart 3.0.
