### ISSUE TITLE
Resolving dependencies issue

### ISSUE THREAD

**Issue by myThorsten** [onepub-dev/dcli#219]
Hello,
first, thank you very much for this great project. I was using dcli with great success until I upgraded the flutter version. I had to update a lot of dependencies, and now I am stuck with this:
`Because every version of flutter_test from sdk depends on test_api 0.5.1 and dcli >=3.0.2 depends on test_api ^0.6.0, flutter_test from sdk is incompatible with dcli >=3.0.2.`
and the version solving fails.

From the pubspec.yaml:
```
dev_dependencies:
  args: ^2.3.1
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  dart_appwrite: ^8.0.0
  dcli: ^3.0.3                                <-----
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8
  flutter_test:                                <-----
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  mockito: ^5.3.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6
  yaml: ^3.1.2
```

Flutter is on version 3.10.6.

Apparently I'm the only one having this problem, and I find that very strange, since any flutter application should have flutter_test and dcli interfering with each other. Anyway, it would be great if someone has a tip for me.
